name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./nunflix-nextjs-frontend
        run: bun install

      - name: Lint
        working-directory: ./nunflix-nextjs-frontend
        run: bun lint

      - name: Type Check
        working-directory: ./nunflix-nextjs-frontend
        run: bun tsc --noEmit

      - name: Build
        working-directory: ./nunflix-nextjs-frontend
        run: bun run build

      - name: Push to Supabase
        if: github.ref == 'refs/heads/main'
        working-directory: ./nunflix-nextjs-frontend
        run: npx supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: npx vercel-cli deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
